//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici_dil_detay
    {
        public int id { get; set; }
        public Nullable<int> dil_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
    
        public virtual tbl_dil tbl_dil { get; set; }
        public virtual tbl_kullanici tbl_kullanici { get; set; }
    }
}
