//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rehber_sorgulamaEntities : DbContext
    {
        public rehber_sorgulamaEntities()
            : base("name=rehber_sorgulamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kullanici_dil_detay> kullanici_dil_detay { get; set; }
        public virtual DbSet<rehber_ilce_detay> rehber_ilce_detay { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_aktivite> tbl_aktivite { get; set; }
        public virtual DbSet<tbl_ayarlar> tbl_ayarlar { get; set; }
        public virtual DbSet<tbl_dil> tbl_dil { get; set; }
        public virtual DbSet<tbl_dilseviye> tbl_dilseviye { get; set; }
        public virtual DbSet<tbl_ilce> tbl_ilce { get; set; }
        public virtual DbSet<tbl_otel> tbl_otel { get; set; }
        public virtual DbSet<tbl_tarihiyerler> tbl_tarihiyerler { get; set; }
        public virtual DbSet<tbl_ulke> tbl_ulke { get; set; }
        public virtual DbSet<vw_rehber_dil> vw_rehber_dil { get; set; }
        public virtual DbSet<vw_rehber_sehir_getir> vw_rehber_sehir_getir { get; set; }
        public virtual DbSet<tbl_rehber> tbl_rehber { get; set; }
        public virtual DbSet<vw_rehber_bilgi_getir> vw_rehber_bilgi_getir { get; set; }
        public virtual DbSet<rehber_dil_detay> rehber_dil_detay { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
    }
}
