//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rehber_ilce_detay
    {
        public int ID { get; set; }
        public Nullable<int> rehber_id { get; set; }
        public Nullable<int> ilce_id { get; set; }
    
        public virtual tbl_ilce tbl_ilce { get; set; }
        public virtual tbl_rehber tbl_rehber { get; set; }
    }
}
