//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rehber_dil_detay
    {
        public int id { get; set; }
        public Nullable<int> dil_id { get; set; }
        public Nullable<int> rehber_id { get; set; }
        public Nullable<int> dil_seviyeid { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual tbl_dil tbl_dil { get; set; }
        public virtual tbl_dilseviye tbl_dilseviye { get; set; }
        public virtual tbl_rehber tbl_rehber { get; set; }
    }
}
