//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_otel
    {
        public int otel_id { get; set; }
        public Nullable<int> ilce_id { get; set; }
        public string otel_ad { get; set; }
        public string gun { get; set; }
        public string konum { get; set; }
        public string fotograf { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> onecikanlar { get; set; }
        public string weburl { get; set; }
    
        public virtual tbl_ilce tbl_ilce { get; set; }
    }
}
