//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rehber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_rehber()
        {
            this.rehber_ilce_detay = new HashSet<rehber_ilce_detay>();
            this.rehber_dil_detay = new HashSet<rehber_dil_detay>();
            this.tbl_kullanici = new HashSet<tbl_kullanici>();
        }
    
        public int rehber_id { get; set; }
        public string adsoyad { get; set; }
        public string email { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public string baslama_saati { get; set; }
        public string bitis_saati { get; set; }
        public Nullable<short> yas { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string parabirimi { get; set; }
        public string fotograf { get; set; }
        public Nullable<int> onecikanlar { get; set; }
        public string cv_aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rehber_ilce_detay> rehber_ilce_detay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rehber_dil_detay> rehber_dil_detay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kullanici> tbl_kullanici { get; set; }
    }
}
