//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ilce()
        {
            this.rehber_ilce_detay = new HashSet<rehber_ilce_detay>();
            this.tbl_aktivite = new HashSet<tbl_aktivite>();
            this.tbl_otel = new HashSet<tbl_otel>();
            this.tbl_tarihiyerler = new HashSet<tbl_tarihiyerler>();
            this.tbl_kullanici = new HashSet<tbl_kullanici>();
        }
    
        public int ilce_id { get; set; }
        public string ilce_ad { get; set; }
        public string fotograf { get; set; }
        public Nullable<int> onecikanlar { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rehber_ilce_detay> rehber_ilce_detay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aktivite> tbl_aktivite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_otel> tbl_otel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tarihiyerler> tbl_tarihiyerler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kullanici> tbl_kullanici { get; set; }
    }
}
