//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kullanici()
        {
            this.kullanici_dil_detay = new HashSet<kullanici_dil_detay>();
        }
    
        public int kullanici_id { get; set; }
        public string kullaniciad { get; set; }
        public string adsoyad { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<int> yas { get; set; }
        public Nullable<int> dil_no { get; set; }
        public Nullable<int> ilce_no { get; set; }
        public Nullable<int> ulke_no { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> kisi_sayisi { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
        public Nullable<int> rehber_id { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<System.DateTime> form_tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_dil_detay> kullanici_dil_detay { get; set; }
        public virtual tbl_dil tbl_dil { get; set; }
        public virtual tbl_ilce tbl_ilce { get; set; }
        public virtual tbl_rehber tbl_rehber { get; set; }
        public virtual tbl_ulke tbl_ulke { get; set; }
    }
}
