//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rehber_dil
    {
        public int dil_id { get; set; }
        public Nullable<int> rehber_id { get; set; }
        public string dil_ad { get; set; }
        public string dil_seviye { get; set; }
    }
}
