//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehbersorgulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rehber_sehir_getir
    {
        public int rehber_id { get; set; }
        public int ilce_id { get; set; }
        public string adsoyad { get; set; }
        public string fotograf { get; set; }
        public string ilce_ad { get; set; }
    }
}
